/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class IdMapIndex {
  /**
   * Construct an `IdMapIndex`.
   *
   * Same `dim`/`bitWidth` semantics as `TurboQuantIndex`.
   */
  constructor(dim?: number | undefined | null, bitWidth?: number | undefined | null)
  /**
   * Add vectors with stable external ids.
   *
   * `vectors` — flat row-major `Float32Array`.
   * `ids`     — `BigUint64Array` with the same element count as the
   *             number of rows in `vectors` (`vectors.length / dim`).
   * `dim`     — required when the index is still lazy.
   */
  addWithIds(vectors: Float32Array, ids: BigUint64Array, dim?: number | undefined | null): void
  /**
   * Remove the vector with the given external id.
   *
   * Returns `true` if the id was present, `false` otherwise.
   * Negative BigInts and values that exceed u64 are definitively absent —
   * they cannot alias any stored u64 id, so `remove` returns `false`
   * without touching the index.
   */
  remove(id: bigint): boolean
  /**
   * Test whether the index contains the given external id.
   * Negative BigInts and values that exceed u64 are definitively absent.
   */
  contains(id: bigint): boolean
  /**
   * Search for the top-`k` nearest ids for each query.
   *
   * Optional `allowlist` restricts the result set to those external ids.
   */
  search(queries: Float32Array, k: number, options?: IdSearchOptions | undefined | null): IdSearchResult
  /** Warm up search caches. */
  prepare(): void
  /** Serialise to a `.tvim` file. */
  write(path: string): void
  /** Load an `IdMapIndex` from a `.tvim` file. */
  static load(path: string): IdMapIndex
  /** Number of vectors in the index. */
  get length(): number
  /** Vector dimensionality, or `null` for a lazy uncommitted index. */
  get dim(): number | null
  /** Quantisation bit-width (2, 3, or 4). */
  get bitWidth(): number
}

export declare class TurboQuantIndex {
  /**
   * Construct a `TurboQuantIndex`.
   *
   * - `dim` — vector dimensionality (must be a positive multiple of 8).
   *   Omit or pass `null`/`undefined` for a lazy index that commits its
   *   dim on the first `add` call.
   * - `bitWidth` — quantisation precision: `2`, `3`, or `4` (default `4`).
   */
  constructor(dim?: number | undefined | null, bitWidth?: number | undefined | null)
  /**
   * Add vectors to the index.
   *
   * `vectors` is a flat row-major `Float32Array` of length `n * dim`.
   * On a lazy index, `dim` is required on the first call and commits the
   * index dimensionality.
   */
  add(vectors: Float32Array, dim?: number | undefined | null): void
  /**
   * Run a top-`k` search against the index.
   *
   * `queries` is a flat row-major `Float32Array` of length `nq * dim`.
   * The optional `mask` is a `boolean[]` of length equal to `this.length`
   * that restricts the candidates to `true` slots.
   */
  search(queries: Float32Array, k: number, options?: SearchOptions | undefined | null): SearchResult
  /**
   * Remove the vector at `idx` in O(1) by swapping with the last vector.
   *
   * Returns the old index of the moved vector.
   * Throws `INDEX_OUT_OF_RANGE` if `idx >= this.length`.
   */
  swapRemove(idx: number): number
  /**
   * Warm up search caches so the first `search` call does not pay the
   * one-time initialisation cost.
   */
  prepare(): void
  /** Serialise the index to `path`. */
  write(path: string): void
  /** Load an index from `path`. */
  static load(path: string): TurboQuantIndex
  /** Number of vectors in the index. */
  get length(): number
  /** Vector dimensionality, or `null` for a lazy uncommitted index. */
  get dim(): number | null
  /** Quantisation bit-width (2, 3, or 4). */
  get bitWidth(): number
}

/** Options bag for `IdMapIndex.search`. */
export interface IdSearchOptions {
  /** Restrict results to these external ids. */
  allowlist?: BigUint64Array
}

/** Search result returned by `IdMapIndex.search`. */
export interface IdSearchResult {
  /** Flat row-major scores: nq × k. */
  scores: Float32Array
  /** Flat row-major external ids (u64 as BigInt): nq × k. */
  ids: BigUint64Array
  /** Number of queries. */
  nq: number
  /** Effective k. */
  k: number
}

/** Options bag for `TurboQuantIndex.search`. */
export interface SearchOptions {
  /** Boolean mask of length `index.length`. Only `true` slots are eligible. */
  mask?: Array<boolean>
}

/** Search result returned by `TurboQuantIndex.search`. */
export interface SearchResult {
  /** Flat row-major scores: nq × k. */
  scores: Float32Array
  /** Flat row-major slot indices (i64 as BigInt): nq × k. */
  indices: BigInt64Array
  /** Number of queries. */
  nq: number
  /**
   * Effective k (may be less than requested k if index is small or mask
   * restricts the eligible set).
   */
  k: number
}
